//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TapFast2.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TapFast2.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Removed.
        /// </summary>
        public static string AdsRemoved {
            get {
                return ResourceManager.GetString("AdsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade game Options.
        /// </summary>
        public static string ArcadeGameOptionsTitle {
            get {
                return ResourceManager.GetString("ArcadeGameOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade Leaderboard.
        /// </summary>
        public static string ArcadeLeaderboard {
            get {
                return ResourceManager.GetString("ArcadeLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        public static string CurrentScore {
            get {
                return ResourceManager.GetString("CurrentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy (Bored).
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sound.
        /// </summary>
        public static string EnableSound {
            get {
                return ResourceManager.GetString("EnableSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 seconds.
        /// </summary>
        public static string FifteenSeconds {
            get {
                return ResourceManager.GetString("FifteenSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Difficulty.
        /// </summary>
        public static string GameDifficulty {
            get {
                return ResourceManager.GetString("GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game highscore: {0}.
        /// </summary>
        public static string GameHighscore {
            get {
                return ResourceManager.GetString("GameHighscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game mode: {0}.
        /// </summary>
        public static string GameMode {
            get {
                return ResourceManager.GetString("GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Time.
        /// </summary>
        public static string GameTime {
            get {
                return ResourceManager.GetString("GameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard (Brave).
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible (I Dare You).
        /// </summary>
        public static string Impossible {
            get {
                return ResourceManager.GetString("Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string Leaderboard {
            get {
                return ResourceManager.GetString("Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal (Curious).
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ads.
        /// </summary>
        public static string RemoveAds {
            get {
                return ResourceManager.GetString("RemoveAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save score.
        /// </summary>
        public static string SaveScore {
            get {
                return ResourceManager.GetString("SaveScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string ScoreSaved {
            get {
                return ResourceManager.GetString("ScoreSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 seconds.
        /// </summary>
        public static string SixtySeconds {
            get {
                return ResourceManager.GetString("SixtySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Off.
        /// </summary>
        public static string SoundOff {
            get {
                return ResourceManager.GetString("SoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound On.
        /// </summary>
        public static string SoundOn {
            get {
                return ResourceManager.GetString("SoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Options.
        /// </summary>
        public static string StandardGameOptionsTitle {
            get {
                return ResourceManager.GetString("StandardGameOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 seconds.
        /// </summary>
        public static string ThirtySeconds {
            get {
                return ResourceManager.GetString("ThirtySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your highscore: {0}.
        /// </summary>
        public static string YourHighscore {
            get {
                return ResourceManager.GetString("YourHighscore", resourceCulture);
            }
        }
    }
}
